[package]
distribution = "2201.12.4"
org = "ballerinax"
name = "mistral"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-mistral"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
